version: '3.8'
services:
  server:
    container_name: monorepo-server
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    env_file:
      - .env
    environment:
      - GO_ENV
    ports:
      - 9000:9000
    volumes:
      - .:/go/src/server
      - ../sqlite/dev.sqlite3:/go/src/sqlite/sqlite3
    command: go run .