name: deploy

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
    - name: Configure docker to use the gcloud cli
      run: gcloud auth configure-docker --quiet
    - name: build and push
      id: build_push
      uses: ./.github/actions/build_push_image
      with:
        image_url: gcr.io/project_id/image_name
        dockerfile_path: ./server/docker/Dockerfile
        build_path: .
    - name: update cloud run job of weekly
      uses: ./.github/actions/update_cloudrun
      with:
        service_name: monorepo-server
        project: monorepo
        region: asia-northeast1